DCD-1434: Removed version 9 from DBEngineVersion
atlassian/quickstart-atlassian-jira pull request #101
Opened 2022-01-11 23:29 UTC by jjeongatl

Remove Postgres version 9 as the version will be EOL

2022-01-12 03:29 UTC, nghazali approved these changes

2022-01-13 05:45 UTC, errcode1202 requested changes

2022-01-13 05:45 UTC, errcode1202 commented on templates/quickstart-jira-dc-with-vpc.template.yaml
> +    Description: "The database engine version to use; we'll install a suitable minor version for your chosen engine. Make sure that the Jira version you're installing supports the database engine sel
```suggestion
    Description: "The database engine version to use; we'll install a suitable minor version for your chosen engine. Make sure that the Jira version you're installing supports the database engine selected. Check https://confluence.atlassian.com/x/bqr1Nw to verify this. (Warning: Amazon RDS for PostgreSQL 9.6 will reach end of life on January 31st, 2022. Deployments after this date should not be made using this version. If you wish to upgrade to a major version from 9 see: https://confluence.atlassian.com/x/1IRlQQ)"
```

2022-01-13 05:45 UTC, errcode1202 commented on templates/quickstart-jira-dc.template.yaml
> +    Description: "The database engine version to use; we'll install a suitable minor version for your chosen engine. Make sure that the Jira version you're installing supports the database engine sel
Same suggestion as above

2022-01-13 06:17 UTC, jjeongatl commented on templates/quickstart-jira-dc.template.yaml
> +    Description: "The database engine version to use; we'll install a suitable minor version for your chosen engine. Make sure that the Jira version you're installing supports the database engine sel
```suggestion
    Description: "The database engine version to use; we'll install a suitable minor version for your chosen engine. Make sure that the Jira version you're installing supports the database engine selected. Check https://confluence.atlassian.com/x/bqr1Nw to verify this. (Warning: Amazon RDS for PostgreSQL 9.6 will reach end of life on January 31st, 2022. Deployments after this date should not be made using this version. If you wish to upgrade to a major version from 9 see: https://confluence.atlassian.com/x/1IRlQQ)"
```

2022-01-13 06:23 UTC, merged